# Generated by Django 6.0.4 on 2026-04-25 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
