# Generated by Django 6.0.4 on 2026-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_area_propiedad_ciudad_propiedad_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
