# Generated by Django 6.0.4 on 2026-05-01 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_propiedad_imagen_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['-id'], 'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baños'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habitaciones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Habitaciones'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='parqueadero',
            field=models.BooleanField(blank=True, null=True, verbose_name='Parqueadero'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Área (m²)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Imagen (archivo)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen (URL externa)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio (COP)'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('lote', 'Lote'), ('finca', 'Finca'), ('local', 'Local'), ('bodega', 'Bodega')], max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección / sector'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
