# Generated by Django 6.0.4 on 2026-05-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='modalidad',
            field=models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo')], default='venta', max_length=20, verbose_name='Modalidad'),
        ),
    ]
