# Generated by Django 6.0.4 on 2026-05-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_favorito_modalidad'),
        ('propiedades', '0007_propiedad_modalidad_propiedad_video_url'),
    ]

    operations = [
    ]
