# Generated by Django 6.0.4 on 2026-05-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_merge_20260502_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='modalidad',
        ),
    ]
