# Generated by Django 6.0.4 on 2026-06-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0010_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Enviado el')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-creado'],
            },
        ),
    ]
