# Generated by Django 6.0.4 on 2026-08-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0011_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Precio (COP)'),
        ),
    ]
