# Generated by Django 6.0.4 on 2026-08-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0012_alter_propiedad_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(verbose_name='URL de imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de propiedad',
                'verbose_name_plural': 'Imágenes de propiedades',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
